stages:
  - pdf
  - image
  - deploy

build-latex:
  image: aergus/latex:latest
  stage: pdf
  script:
    - latexmk -pdf -synctex=1 -interaction=nonstopmode -file-line-error --shell-escape ./main.tex
  artifacts:
    paths:
      - "*.pdf"

build-image:
  image:
    name: debian:stable-slim
    entrypoint: [""]
  stage: image
  script:
    - convert main.pdf main.png
  artifacts:
    paths:
      - "*.png"
pages:
  stage: deploy
  script:
    - mkdir public
    - cp *.pdf public
    - cp *.png public
  artifacts:
    paths:
      - public
  only:
    - master
