stages:
  - pdf
  - image
  - deploy

build-latex:
  image: aergus/latex:latest
  stage: pdf
  script:
    - latexmk -pdf -synctex=1 -interaction=nonstopmode -file-line-error --shell-escape ./cv.*.tex
  artifacts:
    paths:
      - "*.pdf"

build-image:
  image:
    name: debian:stable-slim
    entrypoint: [""]
  stage: image
  before_script:
    - apt update
    - apt install -y --no-install-recommends imagemagick ghostscript
  script:
    - mogrify -density 300 -depth 8 -quality 100 -format png *.pdf
  artifacts:
    paths:
      - "*.png"
pages:
  stage: deploy
  script:
    - mkdir public
    - cp *.pdf public
    - cp cv.en.pdf public/main.pdf
    - cp *.png public
  artifacts:
    paths:
      - public
  only:
    - master
